XENONnT/xedocs

xedocs/schemas/corrections/relative_light_yield.py
Added Schema for relative light yield
=> Add relative light yield schema

.github/workflows/ci-tests.yml, poetry.lock, pyproject.toml, scripts/api_server.py, tests/test_corrections.py, tests/test_xedocs.py, xedocs/__init__.py, xedocs/_settings.py, xedocs/api.py, xedocs/contexts.py, xedocs/schemas/__init__.py, xedocs/schemas/base_schemas.py, xedocs/storage.py, xedocs/utils.py, xedocs/xedocs.py
Make data access contexts to allow for access to different data sources such as production and staging databases.
=> Refactor data access

xedocs/schemas/corrections/se_gains.py
Adding single electron gain schema
=> Add se gain

xedocs/schemas/corrections/__init__.py, xedocs/schemas/corrections/avg_se_gain.py, xedocs/schemas/corrections/se_gains.py
Adding schema for average single electron gain
=> Avg se gain schema

xedocs/xedocs.py
Filter out the protocol kwargs to only use index fields for querying documents.
=> Better URLConfigs protocol

README.rst, xedocs/schemas/corrections/position_reconstruction.py
Updating README Documentation in github will now update it in the readthedocs page too.
=> Updating readme

xedocs/_settings.py
API URL was not being formatted correctly
=> Fix api url

xedocs/schemas/corrections/__init__.py, xedocs/schemas/corrections/bayes_model.py
Seems like it was a correction that for some reason did not get saved the first time around
=> Adding Bayes Model

xedocs/widgets.py
leftover in widgets from refactoring of rframe
=> Remove underscore from limit and skip kwargs

xedocs/xedocs.py
Should fix error with urlconfigs
=> check if class before checking if subclass

xedocs/databases/local.py, xedocs/xedocs.py
Always load the local repo. This is useful in cases where no internet connection is available and we dont want to crash straxen
=> Alway load local

xedocs/schemas/corrections/base_corrections.py, xedocs/schemas/corrections/electron_diffusion_cte.py
This addresses #44 
Fields in the __MUTABLE__ tuple can be changed
=> Add __MUTABLE__ to corrections and use for pre_update

xedocs/__init__.py
the warning for missing gui can be annoying
=> switch warning to debug

xedocs/schemas/__init__.py, xedocs/schemas/historian_reader.py
Add schema for historian reader configurations
=> Historian reader

poetry.lock, xedocs/_settings.py, xedocs/_straxen_plugin.py, xedocs/data_locations/github.py, xedocs/data_locations/mongodb.py, xedocs/xenon_config.py
Remove utilix dependency by reading the xenon_config file directly.
=> Read xenon config file directly

xedocs/utils.py
This will improve performance when accessing github repos
=> lazy accessor cache result of list to dataframe conversion

xedocs/_straxen_plugin.py, xedocs/data_locations/data_folder.py, xedocs/data_locations/github.py, xedocs/databases.py, xedocs/dispatchers.py, xedocs/json_records.py, xedocs/regex_dispatcher.py, xedocs/utils.py
Add support for a local data folder
=> add local folder support

xedocs/clock.py, xedocs/dispatchers.py, xedocs/schemas/corrections/base_corrections.py
This PR add TZ normalization to the "time" and "date_created" field validation.
=> Normilize time and date created

xedocs/xedocs.py
Adds a dry flag to insert_docs so we can check if a file will be saved without saving it (need to approve change in rframe before this will work.)
=> add dry option to insert_docs

xedocs/utils.py
In cases when you want to load all the data, such as tests, you dont need all the documents in memory since you dont want to do any advanced queries. Since it can be memory intensive for large collections like the pmt gains , we want to allow iterative access to each file independently.
Add iterator method over files for LazyFileAccessor to make it easier to iterate over all files without loading all data into memory.
=> Add iterative file access

xedocs/schemas/corrections/s2_pattern_maps.py
To fix the document sync error.
=> Add fmt='binary' to s2 pattern map

xedocs/schemas/corrections/base_references.py, xedocs/schemas/corrections/s1_xyz.py
Related to https://github.com/XENONnT/corrections/pull/232.
=> Allow different format for s1_xyz_maps

xedocs/schemas/corrections/implementations/__init__.py, xedocs/schemas/corrections/implementations/se_gain_partition.py
New schema to handle different definitions of AB and CD partition for SEG
=> schema for SEG partitions

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
Just bumping version from 0.2.27->0.2.28
=> Bump version to 0.2.28

xedocs/schemas/corrections/implementations/__init__.py, xedocs/schemas/corrections/implementations/test_correction.py
Adds a correction so we can test the new the direct method of inserting data into xedocs
=> Add test correction

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
Regular version bumping to include detector_operations schema (#133)
=> Bump to v.0.2.31

tests/test_corrections.py, xedocs/schemas/corrections/implementations/position_reconstruction.py
Following https://github.com/XENONnT/corrections/pull/314#issuecomment-2582918320
=> Only use `"cnf"`, remove `"flow"`

pyproject.toml, xedocs/__init__.py
=> bump xedocs version

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
Bump to version 0.2.34 to patch some pypi issues.
=> Bump version: 0.2.33 → 0.2.34

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
Just bumping version to 0.2.35
=> Bump to v0p2p35

.github/workflows/publish.yml
=> Revert "Bump JRubics/poetry-publish from 2.0 to 2.1"

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
=> Bump version: 0.2.37 → 0.2.38

xedocs/utils.py
=> Remove prints

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
Regular xedocs bump for peak reconstruction bias schema.
=> Bump to v0.2.40

.bumpversion.cfg, HISTORY.rst, pyproject.toml, xedocs/__init__.py
I did something silly with the previous release. I branched before pulling the peak reconstruction commit. 
@GiovanniVolta, can you approve again please. Sorry 🥲
=> Bump patch
