XENONnT/xedocs

- xedocs/xedocs.py
Since irrelevent kwargs may be passed to the xedocs protocol, lets filter them before applying the query just to be safe
> Filter labels before using them for query

- xedocs/databases/api.py
- xedocs/databases/github.py
Since github and API may not be accessible from dali worker nodes, lets load them only if explicitly requested by user with e.g:
`XEDOCS_GITHUB_PRIORITY=3`
`XEDOCS_API_PRIORITY=2`
> Dont load api and github datasources by default

- xedocs/_straxen_plugin.py
bug in the URLConfig protocol, called filter_kwargs with reversed order of arguments
> call filter_kwargs with correct arg order

- xedocs/_settings.py
- xedocs/schemas/corrections/base_references.py
- xedocs/schemas/corrections/bayes_model.py
- xedocs/schemas/corrections/position_reconstruction.py
Some corrections were overriding the already defined time index, this removed the time validator function in those corrections resulting in no auto conversion from run_id to time.
> Remove superfluous time index definitions

- xedocs/xedocs.py
The function for fetching a default datasource was not being registered to the xedocs namespaces. This PR fixes that so that functions that rely on the existence of a default datasource will work.
> add default datasource

- xedocs/schemas/corrections/som_network.py
Add a schema to use in the near future for a peaklet classification using a Self-Organizing Map neural network.
> make SOM schema

- xedocs/schemas/corrections/__init__.py
- xedocs/schemas/corrections/hotspot_veto.py
- xedocs/schemas/corrections/hotspot_veto_cut.py
I think this might be the first a few time dependent cuts people will want to add to xedocs, should we make a separate folder for these cuts since they are not really corrections?
> hotspot veto

- xedocs/schemas/corrections/__init__.py
- xedocs/schemas/corrections/photoionization_strength.py
As @xzh19980906 will show [today](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:zihao:sr1_s2aft_photonionization_correction) the time-dependent corrections can be build using linear correlation with photoionization strength. I propose we store these values too in the corrections, and use this to make all SR1 relative/absolute LY/QY corrections.
> Add photoionization schema

- poetry.lock
- pyproject.toml
- xedocs/data_locations/data_folder.py
- xedocs/data_locations/github.py
- xedocs/utils.py
Adds a new subclass of DataAccessor that supports f-string like templates as paths and will use them to only load the relevant files when a query is made.
This can be useful in cases where you can have hundreds or thousands of files that would take a very long time to load all files.
> Lazy file loading

- xedocs/data_locations/data_folder.py
Add user expansion in the path to a `local_folder `
i.e 
```python
import xedocs
db = xedocs.local_folder("~/corrections")
```
will now work as expected.
> Expand user in path

- xedocs/schemas/corrections/__init__.py
- xedocs/schemas/corrections/z_bias.py
It is a time interval piece-wise correction.
Reference: https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:terliuk:drift_field_z_bias_correction
> Add `z_bias_map` schema

- xedocs/_straxen_plugin.py
Before this, when seeing `raise KeyError(f"No matching documents found for {name}.")`, people will think that the schema is missing. After this PR, I hope the user gets the feeling that it is not the schema that is missing but the data(docs) are missing. The availability of schema is checked at https://github.com/XENONnT/xedocs/blob/cdf7fc922b5cc79dd833903034348fa60457b27f/xedocs/_straxen_plugin.py#L40
> Minor change of error message for unavailable docs

- notebooks/Accessing_and_inserting_data.ipynb
changed the notebook corresponding how to access data based later changes to xedocs. Notebook should now be reproducable with the current version of xedocs
> change db accessing format (notebook)

- xedocs/xedocs.py
The purpose of this pull request is to only allow a particular user to insert ONLINE corrections and no others to protect the integrity of the database. This is not a full proof way of preventing this but it should at least prevent people from changing the database accidentally. We should update everyone to a new version of xedocs before giving out the new username and password
> Test for modifications to ONLINE permisions

- xedocs/data_locations/mongodb.py
- xedocs/xenon_config.py
This PR modifies the MongoDB client to support the following configs with defaults:
```python
max_pool_size: int = 100
socket_timeout: int = 60000
connect_timeout: int = 60000
read_preference: str = "secondaryPreferred"
```
This can be useful eg when submitting massive numbers of jobs to a cluster, each with many threads. you may want to limit the number of connections each process in each job can open to a very small number (the default it 100+2 connections  per process). You may see a small performance hit due to IO delays as queries will need to wait for their turn at an open socket connection but at least you wont overwhelm the mongo server with billions of simultaneous connections.
> Add extra mongodb config when constructing client

- .bumpversion.cfg
- HISTORY.rst
- pyproject.toml
- xedocs/__init__.py
Bump version from 0.2.26 to [0.2.27](https://github.com/XENONnT/xedocs/releases/tag/v0.2.27).
> Update to 0.2.27 test

- xedocs/schemas/detector_numbers.py
Changing DetectorNumbers schema to kind `TimeIntervalCorrections` to move detector_numbers, especially g1 and g2 to `xedocs`.
> Detector numbers

- xedocs/schemas/corrections/implementations/position_reconstruction.py
This pull request is simply to add a field called "flow" to the options regarding the position reconstruction algorithms. For more information about this new model see the following [note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:svetter:conditional_norm_flow_posrec_principle).
> add flow model to pos_rec

- .bumpversion.cfg
- HISTORY.rst
- pyproject.toml
- xedocs/__init__.py
We need a new version release to update the types of machine learning that xedocs will accept for position reconstruction. This is needed to prevent tests in the corrections repo from failing when adding this new correction to the database.
> bump version v0.2.30

- xedocs/schemas/operations_reports/__init__.py
- xedocs/schemas/operations_reports/detector_operations.py
Provides a new schema that RCs can use through the xedocs website to log general operations on the detector. [Requested by ACs and RC](https://xenonnt.slack.com/archives/C016UJZ090B/p1724770994083319). No numerical values can be input and no interpolation is expected. This is a general sort of 'eLog', that can now be accessible for everyone through xedocs.
> Detector Operations Log

- xedocs/schemas/corrections/base_references.py
Keep consistent with: https://github.com/XENONnT/utilix/pull/141
> import mongodownloader from utilix

- xedocs/schemas/corrections/implementations/baseline_samples_nv.py
Otherwise when `export NUMBA_DISABLE_JIT=1` you will see an error:
```
Exception during processing, closing savers and reraising
Traceback (most recent call last):
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/el9.2024.09.1/anaconda/envs/XENONnT_el9.2024.09.1/lib/python3.9/pdb.py", line 1726, in main
pdb._runscript(mainpyfile)
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/el9.2024.09.1/anaconda/envs/XENONnT_el9.2024.09.1/lib/python3.9/pdb.py", line 1586, in _runscript
self.run(statement)
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/el9.2024.09.1/anaconda/envs/XENONnT_el9.2024.09.1/lib/python3.9/bdb.py", line 580, in run
exec(cmd, globals, locals)
File "<string>", line 1, in <module>
File "/home/xudc/analysiscode/straxen_debug/python_scripts/process_memory_usage.py", line …
```
> `baseline_samples_nv` should be int

- xedocs/schemas/corrections/base_references.py
- xedocs/schemas/corrections/implementations/position_reconstruction.py
Since in straxen, we now have [cnf as the new default pos_rec algo](https://github.com/XENONnT/straxen/blob/4d2c89e906e3bcd46c9702ff6700675ddf455bf3/straxen/plugins/defaults.py#L3), we have updated the list of algorithms here in xedocs
> adding cnf

- xedocs/dispatchers.py
- xedocs/utils.py
To be compatible with old format fsspec before v2023.10.0
fsspec newer than that will return `fs.protocol = ("local", "file")` and confuse the dispatches functions like `read_json_files` https://github.com/XENONnT/xedocs/blob/008b018342f9d7cf6adc8e4e9b18f8f66b939c9a/xedocs/dispatchers.py#L65.
> Force to use file protocol in fsspec

- xedocs/utils.py
This [PR](https://github.com/XENONnT/xedocs/pull/155) was meant ot fix the read from local folder but break the sync_db.py.
For instance running:
```
(
source /cvmfs/xenon.opensciencegrid.org/releases/nT/el7.2025.03.1/setup.sh && \
export XENON_CONFIG="/dali/lgrandi/giovo/SR2/xedocs/.xenon_config_corrections" && \
export XEDOCS_SYNC_SCHEMAS=som_classifiers && \
export XEDOCS_TARGET_DB=straxen_db && \
export CONFIG_VERSION=v1 && \
export XEDOCS_SYNC_LOG_FOLDER=./logs && \
python3 sync_db.py
)
```
Before:
```
=== Syncing 'som_classifiers' ===
Grouping by: ['version']
unique: []
unique 2: {'version': []}
Label groups: []
v1
Filtered label combinations to process: []
```
Now:
=== Syncing 'som_classifiers' ===
```
Grouping by: ['version']
unique: ['ONLINE', 'v1', 'v2', 'v3', 'v4', 'v5']
unique …
```
> Fix iter path records

- xedocs/schemas/constants.py
- xedocs/schemas/corrections/implementations/__init__.py
- xedocs/schemas/corrections/implementations/peak_reconstruction_bias.py
New scheme for peak reconstruction bias. See the [correction repo PR](https://github.com/XENONnT/corrections/pull/380) and private_nt file [here](https://github.com/XENONnT/straxen/pull/1592).
> Peak rec bias schema
